moveit_controller_manager: moveit_ros_control_interface/Ros2ControlManager
moveit_simple_controller_manager:
  controller_names:
    - arm_left_controller
    - arm_right_controller
    - leg_right_controller
    - leg_left_controller
    - torso_controller
    - head_controller
    - gripper_right_controller
    - gripper_left_controller
  arm_left_controller:
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints:
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint
  arm_right_controller:
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
  leg_right_controller:
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints:
      - leg_right_1_joint
      - leg_right_2_joint
      - leg_right_3_joint
      - leg_right_4_joint
      - leg_right_5_joint
      - leg_right_6_joint
      - leg_right_7_joint
  leg_left_controller:
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints:
      - leg_left_1_joint
      - leg_left_2_joint
      - leg_left_3_joint
      - leg_left_4_joint
      - leg_left_5_joint
      - leg_left_6_joint
      - leg_left_7_joint  
  gripper_right_controller:
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints:
      - gripper_right_joint
  gripper_left_controller:
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints:
      - gripper_left_joint             
  torso_controller:
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints:
      - torso_1_joint
      - torso_2_joint
  head_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - head_1_joint
      - head_2_joint
trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
